### ISSUE TITLE
IObject: Length Keyword

### ISSUE THREAD

**Issue by MylesSmart** [voodoocreation/ts-deepmerge#17]
Why is the key length a reserved property on IObject? I cannot find a reason why -- hoping for either clarify, or removal :) I am running into issues with my object that has a property called length

**Comment by MylesSmart** [comment]
Thank you so much for your quick response :)

**Comment by voodoocreation** [comment]
[Fixed in `2.0.4`](https://github.com/voodoocreation/ts-deepmerge/releases/tag/2.0.4) 🙏
