### ISSUE TITLE
deepmerge 2.0.6 requires node 16?

### ISSUE THREAD

**Issue by sesam** [voodoocreation/ts-deepmerge#18]
#0 90.24 error ts-deepmerge@2.0.6: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.20.0"

We were running 2.0.1 on Google cloud with node 14 up until last rebuild which somehow replaced 2.0.1 with 2.0.6 through firebase-functions-test.

**Comment by voodoocreation** [comment]
The `ts-deepmerge` project's `package.json` was missing the `engines` definition, so it was added. Node 16 is the current LTS version, so it's recommended to upgrade your version of Node to align to the current supported version.

**Comment by sesam** [comment]
Ok, thanks. Still it might make sense to do a major version bump SemVer style :). I can lock down to 2.0.5 in the meantime I guess.

**Comment by voodoocreation** [comment]
Yeah sorry about that! I didn't realise that it was going to cause issues. I'll publish a new patch version to remove the `engines` definition, then publish a new major version with the Node 16 definition.

**Comment by sesam** [comment]
Awesome!

**Comment by voodoocreation** [comment]
I'll actually use `>=14` to be honest, because it does actually work in the previous LTS version. I was mostly just hoping to encourage consumers to migrate to the current LTS 😅 

Sorry about the hassle! 

Have published `2.0.7` with the removed `engines` definition, plus `3.0.0` with the Node 14 requirement.

**Comment by voodoocreation** [comment]
Thanks for bringing this to my attention by the way! 🙏
