### ISSUE TITLE
Source Map error when using Webpack 5

### ISSUE THREAD

**Issue by aaronmcdavid** [voodoocreation/ts-deepmerge#19]
When ts-deepmerge is used in a Webpack 5 project and the project is built, Webpack generates the following warning:

`Failed to parse source map from '«path»\node_modules\ts-deepmerge\src\index.ts' file: Error: ENOENT: no such file or directory, open '«path»\node_modules\ts-deepmerge\src\index.ts'`

The fix is easy:  change `"sourceMap": true,` to     `"sourceMap": false,` in `tsconfig.json`.

**Comment by voodoocreation** [comment]
Oh interesting, I haven't encountered this in any of the Webpack 5 projects I've used this package in, though that's quite possibly down to using a different configuration from you.

I can see that the source maps are in fact being bundled into the package and indeed reference `/src/index.ts` which isn't bundled in with the package. Will get a new version out soon where the source maps aren't included 🙏

**Comment by voodoocreation** [comment]
[Version `4.0.0`](https://github.com/voodoocreation/ts-deepmerge/releases/tag/4.0.0) removes the source maps.

It seemed the source maps were previously enabled to allow the Jest coverage report to work, so I've shifted that to the Jest config's TS overrides instead 👌
