### ISSUE TITLE
It's not clear from the readme what happens when there are conflicts in the merged objects

### ISSUE THREAD

**Issue by expipiplus1** [voodoocreation/ts-deepmerge#2]
Does it bias towards the first or last or error?

**Comment by voodoocreation** [comment]
I'm not quite sure I understand the scenario. Could you please provide an example of such a conflict?

**Comment by expipiplus1** [comment]
Something like: `merge ({a:1;},{a:2;})`

**Comment by voodoocreation** [comment]
Ahh yeah, it will result in `a` being overwritten with the value from the second argument (`2`). It will merge all array/object values, but values such as numbers and strings will be overwritten in the order of the arguments you provide the function with.

I'll update the readme example to include this scenario.

**Comment by voodoocreation** [comment]
Included a more descriptive README.md in version `1.0.6`.

**Comment by expipiplus1** [comment]
Thanks!
